### ISSUE TITLE
Random characters / names everywhere?

### ISSUE THREAD

**Issue by cdrage** [CentOS/container-pipeline-service#442]
It seems that there are *a lot* of random tagged images being created: https://registry.centos.org/repository/arrfab/nanoc

Which seems to  be very cluttering. What use are these images, and can they be removed? Personally, I wouldn't like all these images taking up space.

**Comment by mohammedzee1000** [comment]
@cdrage these are temporary tags that are generated during builds. I have been working on a garbage collector for this  (https://github.com/CentOS/container-pipeline-service/pull/416) which should regularly clean up the unnecessary tags.

**Comment by cdrage** [comment]
@mohammedzee1000 I just built my first container that linked to here: https://registry.centos.org/pipeline-logs/ZGE3NWZmMmIzMT/

I don't think these are temporary if they're being used to send to emails...

Shouldn't it be: https://registry.centos.org/pipeline-logs/cdrage/mosh-centos7/latest instead?

**Comment by bamachrn** [comment]
@cdrage the links to the logs are intentionally made random like that. Plan is the user who is having the URL in email, can only look for the build logs. 
https://registry.centos.org/pipeline-logs/cdrage/mosh-centos7/latest should show all the details about the image in registry. But build logs can only be seen using https://registry.centos.org/pipeline-logs/ZGE3NWZmMmIzMT/.
This is by design, but we can always re-think 👍

**Comment by cdrage** [comment]
@bamachrn Ah okay. Kind of odd since it's all suppose to be open source (and so should the logs) :+1: I'm interested in re-thinking / re-implementing!

**Comment by kbsingh** [comment]
need to also think about versioning and holding log data, if we just do it for a tag, we'd need to think about howto manage that, since tag's can be replaced.

**Comment by bamachrn** [comment]
This would be handled as we retrieve logs from the cluster using API end points.
