### ISSUE TITLE
Cleanup variables + actual hosts file / problems with setting multiple variables within the hosts file.

### ISSUE THREAD

**Issue by cdrage** [CentOS/container-pipeline-service#466]
Okay... So variables from `group_vars/all` is overriding ANY variables which are being set within the hosts file..

For example, if I set:

```
test=True
```

Within my `hosts.sample` file. It will *never* propagate as `True` since `group_vars/all` is set to False.

All variables from within `group_vars/all` should instead be located in the example `hosts.sample` file rather than being located in a separate folder.

**Comment by navidshaikh** [comment]
Here are the repeating variables between hosts.sample and group_vars/all

```
public_registry
intranet_registry
rsync_ssh_opts
setup_nfs
log_level
db_host
allowed_hosts
```

**Comment by navidshaikh** [comment]
I think we should keep few variables in `group_vars/all` which not really required to be changed for usual development and deployment. For example, the `postgresql_image` we use, since we have tested the particular image with our workers and that doesn't need to be changed per deployment (basically land in inventory file), however if needed, can be updated in `group_vars/all`.

@bamachrn WDYT ?
