### ISSUE TITLE
Handle queue disconnects from inside containerised workers

### ISSUE THREAD

**Issue by mohammedzee1000** [CentOS/container-pipeline-service#479]
We need to figure out a better way of handling disconnects from the beanstalkd tube. There have been issues where, after the disconnect, the worker stops working completely and needs to be restarted to restore service. 

We should:
1. Put in better error handling and recovery into the queuing system inside containerised workers.
2. Update monitoring to ensure container restarts if such failures cannot be recovered from.
3. Alert us if recovery does not occur after multiple restarts

Note: so long as program is running inside container, it does not die. Once we move to openshift, liveliness and readiness probes should offer us this functionality.  But for now, we need an interm measure.

**Comment by navidshaikh** [comment]
Notice that we have a decorator `retry` and all the queue operations are decorated with `retry.
The decorator tries to ensure the operations performed in queue utility methods are executed by catching the exception types via `[beastalkdc.SocketErro, beaslktac.DeadlineSoon, QueueEmptyexception]`. 

The current arose, because there was an `AttributeError`, now why would AttributeError come? Possibility is
 - The object was intialized and the connection is lost meanwhile another method could be called upon the object. (in this case, the operation was `obje._stats_tube`).

What can be done? I think we can add the decorator to hold one more exception and retry, i.e. `AttributeError`.
