### ISSUE TITLE
Consolidate / validate the atomic scanner results

### ISSUE THREAD

**Issue by navidshaikh** [CentOS/container-pipeline-service#48]
As part of the pipeline, one of the step is to scan built container image using the atomic scanner(s) we have. The results generated by atomic scanner need to be consolidated and presented. 

If atomic scanner is providing the scan result score, and based on the scan score / validation, we may need to notify the author about issues.

The aim of this issue is to answer following questions:
  - What do we do with the results of atomic scanners?
  - Decide, If there are results from scanner which should block the pipeline progress of image under process.
  - How do we present the results of atomic scanners?

**Comment by kbsingh** [comment]
**What do we do with the results of atomic scanners?**

The entire output, per scanner, should be added to both the job-log as well as to the notify-log, so the user gets the relevant info in the notifcation email, and also has access to the content via the view-metadata feature ( wip ); if the content itself can be summarised, then only the summary should be sent over, and details aggregated on the log. Given that we will likely have a directory per job for the various lots, each scanner might be able to own a specific filename that maps to that specific scan job, inside that directory.

**Decide, If there are results from scanner which should block the pipeline progress of image under process.**

No, Scanner output should not block the request at this point. However, given enough confidence in the system this might be something we want to look at down the road. Since we cant do any security asserts at this point, we might want to also factor that in.

**How do we present the results of atomic scanners?**

As a way to get started, we should just present the relevant logs; as a second stage, we should grow a common web-ui to present this information. Note that each scanner should itself be usable on the cli outside of the pipeline service, so should present its log format in a human parseable way if at all possible.
